### ISSUE TITLE
bot is crashing when running with a config file

### ISSUE THREAD

**Issue by M0UL** [subzero79/docker-telegram-sonarr-bot#2] opened 2016-01-27 11:19 UTC
the bot keeps crashing when running with a config file. it cashed after finding the config file.

log; http://pastebin.com/ZBqKp4rZ

**Comment by subzero79** [comment] 2016-01-27 11:40
New code has been committed to the original node application, I'll review it tomorrow so I can update the image.
Unfortunately is an automated build so new code in onedrop repo pushes a new image build, so it tends to break frequently

**Comment by subzero79** [comment] 2016-01-28 04:03
I cannot reproduce this, do you have sonarr with password/ssl?

**Comment by M0UL** [comment] 2016-01-28 08:09
i dont use sonarr with a password of ssl.

i am running the docker image on a synology

**Comment by subzero79** [comment] 2016-01-28 10:37
Could be a syntax error in your config.json. Check it again that it doesn't have a missing double quotes or comma missing.

**Comment by M0UL** [comment] 2016-01-28 10:42
i will check it again

edit: check it and found nothing wrong with it

**Comment by subzero79** [comment] 2016-02-02 02:32
If you edit your comments i don't get a notification.

**Comment by subzero79** [comment] 2016-02-02 03:16
If you want you can send me in irc your full config.json as dropbox link to download.

**Comment by M0UL** [comment] 2016-02-06 12:28
i have done this a few days ago

**Comment by subzero79** [comment] 2016-02-06 19:35
So is working for you now?

**Comment by M0UL** [comment] 2016-02-06 20:35
nope

**Comment by subzero79** [comment] 2016-02-06 21:23
There is an email in my github. Send me your config file in a Dropbox link if you want.

**Comment by M0UL** [comment] 2016-02-07 14:12
the email on your profile page does not work

**Closed as completed** 2016-02-09 06:00 UTC
